version: "3"
services:
  app:
    build:
      context: ./
    volumes:
      - node_modules:/app/node_modules
      - .:/app
    command: sh -c "PORT=4000 yarn start"
    ports:
      - "4000:4000"
volumes:
  node_modules:
    driver_opts:
      type: none
      device: ${PWD}/node_modules
      o: bind
