version: "3"
services:
  app:
    build:
      context: ./
    volumes:
      - front_node_modules:/app/node_modules
      - .:/app
    command: sh -c "PORT=4000 yarn start"
    ports:
      - "4000:4000"
volumes:
  front_node_modules:
